# Generated by Django 4.2 on 2023-08-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Academy', 'Academy'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Academy', 'Academy'), ('Other', 'Other')], max_length=10),
        ),
    ]
