# Generated by Django 4.2 on 2023-09-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useraddress_type_alter_userphonenumber_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='type',
            field=models.CharField(choices=[('Other', 'Other'), ('Home', 'Home'), ('Academy', 'Academy'), ('Office', 'Office')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userphonenumber',
            name='type',
            field=models.CharField(choices=[('Other', 'Other'), ('Home', 'Home'), ('Academy', 'Academy'), ('Office', 'Office')], max_length=10),
        ),
    ]
