# Generated by Django 3.2 on 2023-04-23 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20230413_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Productimages', verbose_name='image')),
            ],
        ),
        migrations.RenameModel(
            old_name='ProdactReview',
            new_name='ProdactReviews',
        ),
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('sela', 'sela'), ('New', 'New'), ('Feature', 'Feature')], max_length=10, verbose_name='flag'),
        ),
        migrations.DeleteModel(
            name='ProdactImage',
        ),
        migrations.AddField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_images', to='products.product', verbose_name='product'),
        ),
    ]
