# Generated by Django 3.2 on 2023-04-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20230424_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('New', 'New'), ('Feature', 'Feature'), ('sela', 'sela')], max_length=10, verbose_name='flag'),
        ),
    ]
