# Generated by Django 4.2 on 2023-04-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_quantity_alter_product_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('sela', 'sela'), ('New', 'New'), ('Feature', 'Feature')], max_length=10, verbose_name='flag'),
        ),
    ]
