# Generated by Django 4.2 on 2023-09-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('sela', 'sela'), ('Feature', 'Feature'), ('New', 'New')], max_length=10, verbose_name='flag'),
        ),
    ]
